apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.deployment_config}}
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.org/proxy-body-size: 300M
    nginx.org/client-max-body-size: 300M
    nginx.org/location-snippets: |
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $http_connection;
spec:
  tls:
  - hosts:
    - {{.host}}
    secretName: {{.deployment_config}}-tls
  rules:
  - host: {{.host}}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{.deployment_config}}
          servicePort: 4040
